use ms_compress::{lznt1, xpress_plain};

#[test]
fn lznt1_storage_unit_stops_only_after_a_valid_full_chunk_prefix() {
    let original = vec![b'A'; 8192];
    let encoded = lznt1::compress(&original).unwrap();
    for tail in [0, 0x7f] {
        let mut stored = encoded.clone();
        stored.push(tail);
        let mut output = vec![0; original.len()];
        assert_eq!(
            lznt1::decompress_storage_unit(&stored, &mut output),
            Ok((original.len(), encoded.len()))
        );
        assert_eq!(output, original);
        assert_eq!(
            lznt1::decompress(&stored, &mut output),
            Err(lznt1::Error::TruncatedInput)
        );
    }
}

#[test]
fn lznt1_storage_unit_rejects_damage_before_its_output_boundary() {
    use lznt1::Error;
    let encoded = lznt1::compress(&vec![b'A'; 8192]).unwrap();
    let first_end = 3 + usize::from(u16::from_le_bytes([encoded[0], encoded[1]]) & 0xfff);
    for end in [first_end - 1, encoded.len() - 1] {
        assert_eq!(
            lznt1::decompress_storage_unit(&encoded[..end], &mut [0; 8192]),
            Err(Error::TruncatedInput)
        );
    }
    for (input, error) in [
        (&[0][..], Error::TruncatedInput),
        (&[0, 0x20, 1][..], Error::InvalidData),
        (&[0, 0xb0, 0][..], Error::TruncatedInput),
        (&[2, 0xb0, 1, 0, 0][..], Error::InvalidOffset),
    ] {
        assert_eq!(
            lznt1::decompress_storage_unit(input, &mut [0; 8192]),
            Err(error)
        );
    }
    // Required chunks are not truncated to fit the output capacity.
    let mut raw = vec![0xff, 0x3f];
    raw.extend([b'A'; 4096]);
    assert_eq!(
        lznt1::decompress_storage_unit(&raw, &mut [0; 4095]),
        Err(Error::OutputTooSmall)
    );
    // A single padding byte does not authorize incomplete logical output.
    assert_eq!(
        lznt1::decompress_storage_unit(&[0, 0x30, b'A', 0], &mut [0; 8192]),
        Err(Error::TruncatedInput)
    );
}

#[test]
fn lznt1_storage_unit_validates_the_entire_final_chunk_before_stopping() {
    use lznt1::Error;
    let encoded = lznt1::compress(&[b'A'; 4096]).unwrap();
    for (extra, expected) in [
        // Extra payload enters the final flag group's unused literal positions,
        // so it must not be treated as storage padding after a completed chunk.
        (&[0][..], Error::InvalidData),
        (&[1, 0, 0][..], Error::InvalidData),
    ] {
        let mut damaged = encoded.clone();
        let header = u16::from_le_bytes([damaged[0], damaged[1]]);
        let new_header = header + u16::try_from(extra.len()).unwrap();
        damaged[..2].copy_from_slice(&new_header.to_le_bytes());
        damaged.extend(extra);
        assert_eq!(
            lznt1::decompress_storage_unit(&damaged, &mut [0; 4096]),
            Err(expected)
        );
    }
}

#[test]
fn lznt1_storage_unit_empty_capacity_contract_is_explicit() {
    assert_eq!(lznt1::decompress_storage_unit(&[], &mut []), Ok((0, 0)));
    assert_eq!(
        lznt1::decompress_storage_unit(&[0, 0], &mut []),
        Err(lznt1::Error::OutputTooSmall)
    );
    let encoded = lznt1::compress(&[b'A'; 4096]).unwrap();
    assert_eq!(
        lznt1::decompress_storage_unit(&encoded, &mut [0; 8192]),
        Ok((4096, encoded.len()))
    );
}

type Encoder = fn(&[u8]) -> Result<Vec<u8>, lznt1::Error>;
type Decoder = fn(&[u8], &mut [u8]) -> Result<usize, lznt1::Error>;
const CODECS: [(Encoder, Decoder); 2] = [
    (lznt1::compress, lznt1::decompress),
    (xpress_plain::compress, xpress_plain::decompress),
];

#[test]
fn microsoft_plain_xpress_examples_decode_and_encode() {
    // MS-XCA section 3.1, published examples (not generated by our encoder).
    let alphabet = b"abcdefghijklmnopqrstuvwxyz";
    let mut encoded = vec![0x3f, 0, 0, 0];
    encoded.extend_from_slice(alphabet);
    let mut output = [0; 26];
    assert_eq!(xpress_plain::decompress(&encoded, &mut output), Ok(26));
    assert_eq!(&output, alphabet);
    assert_eq!(xpress_plain::compress(alphabet).unwrap(), encoded);
    let encoded = [
        0xff, 0xff, 0xff, 0x1f, 0x61, 0x62, 0x63, 0x17, 0, 0x0f, 0xff, 0x26, 1,
    ];
    let mut output = [0; 300];
    assert_eq!(xpress_plain::decompress(&encoded, &mut output), Ok(300));
    assert_eq!(output.as_slice(), b"abc".repeat(100));
    assert_eq!(xpress_plain::compress(&output).unwrap(), encoded);
}

#[test]
fn microsoft_lznt1_overlap_example_decodes() {
    // MS-XCA section 3.3, including its terminating NUL literal.
    let encoded = [
        0x38, 0xb0, 0x88, 0x46, 0x23, 0x20, 0x00, 0x20, 0x47, 0x20, 0x41, 0x00, 0x10, 0xa2, 0x47,
        0x01, 0xa0, 0x45, 0x20, 0x44, 0x00, 0x08, 0x45, 0x01, 0x50, 0x79, 0x00, 0xc0, 0x45, 0x20,
        0x05, 0x24, 0x13, 0x88, 0x05, 0xb4, 0x02, 0x4a, 0x44, 0xef, 0x03, 0x58, 0x02, 0x8c, 0x09,
        0x16, 0x01, 0x48, 0x45, 0x00, 0xbe, 0x00, 0x9e, 0x00, 0x04, 0x01, 0x18, 0x90, 0x00,
    ];
    let expected = b"F# F# G A A G F# E D D E F# F# E E F# F# G A A G F# E D D E F# E D D E E F# D E F# G F# D E F# G F# E D E A F# F# G A A G F# E D D E F# E D D\0";
    let mut output = [0; 142];
    assert_eq!(lznt1::decompress(&encoded, &mut output), Ok(142));
    assert_eq!(output.as_slice(), expected);
}

#[test]
fn round_trips_cover_chunk_flag_and_extended_length_boundaries() {
    let mut seed = 0x12345678u32;
    for size in [
        0, 1, 2, 3, 9, 10, 24, 25, 31, 32, 33, 279, 280, 4095, 4096, 4097, 8192, 65538, 65539,
        100000,
    ] {
        let random: Vec<_> = (0..size)
            .map(|_| {
                seed ^= seed << 13;
                seed ^= seed >> 17;
                seed ^= seed << 5;
                seed as u8
            })
            .collect();
        for input in [
            vec![b'a'; size],
            random,
            (0..size).map(|i| (i % 17) as u8).collect(),
        ] {
            for (encode, decode) in CODECS {
                let encoded = encode(&input).unwrap();
                let mut output = vec![0xcc; size + 7];
                assert_eq!(decode(&encoded, &mut output), Ok(size));
                assert_eq!(&output[..size], input);
                assert_eq!(&output[size..], &[0xcc; 7]);
                if size > 0 {
                    assert!(decode(&encoded, &mut vec![0; size - 1]).is_err());
                }
            }
        }
    }
}

#[test]
fn shared_xpress_nibbles_persist_across_flag_groups() {
    // Two length-10 matches share a byte across a group boundary.
    let mut encoded = 0x40000000u32.to_le_bytes().to_vec();
    encoded.push(b'a');
    encoded.extend_from_slice(&[7, 0, 0]);
    encoded.extend_from_slice(&[b'b'; 30]);
    encoded.extend_from_slice(&u32::MAX.to_le_bytes());
    encoded.extend_from_slice(&[7, 0]);
    let mut output = [0; 51];
    assert_eq!(xpress_plain::decompress(&encoded, &mut output), Ok(51));
    assert_eq!(&output[..11], &[b'a'; 11]);
    assert_eq!(&output[11..], &[b'b'; 40]);
}

#[test]
fn malformed_inputs_are_rejected() {
    use lznt1::Error;
    for input in [&[0][..], &[0, 0x20, 1], &[0, 0xb0, 0], &[2, 0xb0, 1, 0, 0]] {
        assert!(lznt1::decompress(input, &mut [0; 4096]).is_err());
    }
    // History resets at each LZNT1 chunk.
    assert_eq!(
        lznt1::decompress(&[0, 0x30, b'a', 2, 0xb0, 1, 0, 0], &mut [0; 4096]),
        Err(Error::InvalidOffset)
    );
    assert_eq!(
        xpress_plain::decompress(&[0xff, 0xff, 0xff, 0xff, 0, 0], &mut [0; 16]),
        Err(Error::InvalidOffset)
    );
    // Invalid extended length below the minimum representable long length.
    assert_eq!(
        xpress_plain::decompress(
            &[0xff, 0xff, 0xff, 0x7f, b'a', 7, 0, 15, 255, 21, 0],
            &mut [0; 4096]
        ),
        Err(Error::InvalidData)
    );
    for (encode, decode) in CODECS {
        let encoded = encode(&b"abc".repeat(100)).unwrap();
        for end in 1..encoded.len() {
            // A prefix may itself be a valid LZNT1 stream, but must never panic.
            let mut output = [0; 300];
            let _ = decode(&encoded[..end], &mut output);
        }
    }
    assert_eq!(lznt1::decompress(&[0, 0, 0, 0], &mut []), Ok(0));
    assert_eq!(
        lznt1::decompress(&[0, 0, 1], &mut []),
        Err(Error::InvalidData)
    );
}

#[test]
fn arbitrary_short_inputs_do_not_panic() {
    for token in 0..=u16::MAX {
        let bytes = token.to_le_bytes();
        for (_, decode) in CODECS {
            let _ = decode(&bytes, &mut [0; 64]);
        }
    }
}
