//! Byte-exact safe-Rust port of classic zlib (madler/zlib 1.3.x) compression for exactly one
//! configuration: `deflateInit2(level 6, Z_DEFLATED, 15, memLevel 8, Z_DEFAULT_STRATEGY)` followed
//! by a single `deflate(Z_FINISH)` over a whole in-memory buffer.
//!
//! The structure follows `deflate.c` (`deflate_slow`, `fill_window`, `longest_match`) and
//! `trees.c` (`_tr_flush_block`, `build_tree`, `gen_bitlen`, ...) so that every tie-breaking
//! decision matches the C implementation. Microsoft Defender VDM containers were produced with
//! this exact encoder, and recompressing their payload reproduces them bit for bit.
//! Adapted from windows-mpsp/src/zlib_deflate.rs: scratch and output storage are
//! borrowed from the caller, and the public entry point writes a gzip wrapper.

use std::sync::OnceLock;

const W_SIZE: usize = 1 << 15;
const W_MASK: usize = W_SIZE - 1;
const WINDOW_SIZE: usize = 2 * W_SIZE;
const HASH_SIZE: usize = 1 << 15;
const HASH_MASK: u32 = (HASH_SIZE as u32) - 1;
const HASH_SHIFT: u32 = 5;
const MIN_MATCH: usize = 3;
const MAX_MATCH: usize = 258;
const MIN_LOOKAHEAD: usize = MAX_MATCH + MIN_MATCH + 1;
const MAX_DIST: usize = W_SIZE - MIN_LOOKAHEAD;
const TOO_FAR: usize = 4096;

// Level 6 configuration_table entry.
const GOOD_LENGTH: usize = 8;
const MAX_LAZY: usize = 16;
const NICE_LENGTH: usize = 128;
const MAX_CHAIN: usize = 128;

const LIT_BUFSIZE: usize = 1 << 14;
const SYM_END: usize = LIT_BUFSIZE - 1;

const LENGTH_CODES: usize = 29;
const LITERALS: usize = 256;
const L_CODES: usize = LITERALS + 1 + LENGTH_CODES;
const D_CODES: usize = 30;
const BL_CODES: usize = 19;
const HEAP_SIZE: usize = 2 * L_CODES + 1;
const MAX_BITS: usize = 15;
const END_BLOCK: usize = 256;
const REP_3_6: usize = 16;
const REPZ_3_10: usize = 17;
const REPZ_11_138: usize = 18;

const EXTRA_LBITS: [u8; LENGTH_CODES] = [
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0,
];
const EXTRA_DBITS: [u8; D_CODES] = [
    0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13,
    13,
];
const EXTRA_BLBITS: [u8; BL_CODES] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 7];
const BL_ORDER: [usize; BL_CODES] = [
    16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
];

/// Static tables generated by `tr_static_init`.
struct Tables {
    length_code: [u8; 256],
    dist_code: [u8; 512],
    base_length: [u16; LENGTH_CODES],
    base_dist: [u16; D_CODES],
    sl_code: [u16; L_CODES + 2],
    sl_len: [u16; L_CODES + 2],
    sd_code: [u16; D_CODES],
    sd_len: [u16; D_CODES],
}

fn bi_reverse(mut code: u32, mut len: u32) -> u32 {
    let mut res = 0;
    loop {
        res |= code & 1;
        code >>= 1;
        res <<= 1;
        len -= 1;
        if len == 0 {
            break;
        }
    }
    res >> 1
}

/// `gen_codes`: assign canonical codes given the bit lengths.
fn gen_codes(code: &mut [u16], len: &[u16], max_code: usize, bl_count: &[u16; MAX_BITS + 1]) {
    let mut next_code = [0u16; MAX_BITS + 1];
    let mut c: u32 = 0;
    for bits in 1..=MAX_BITS {
        c = (c + u32::from(bl_count[bits - 1])) << 1;
        next_code[bits] = c as u16;
    }
    for n in 0..=max_code {
        let l = len[n] as usize;
        if l == 0 {
            continue;
        }
        let nc = next_code[l];
        next_code[l] = nc.wrapping_add(1);
        code[n] = bi_reverse(u32::from(nc), l as u32) as u16;
    }
}

fn tables() -> &'static Tables {
    static T: OnceLock<Tables> = OnceLock::new();
    T.get_or_init(|| {
        let mut t = Tables {
            length_code: [0; 256],
            dist_code: [0; 512],
            base_length: [0; LENGTH_CODES],
            base_dist: [0; D_CODES],
            sl_code: [0; L_CODES + 2],
            sl_len: [0; L_CODES + 2],
            sd_code: [0; D_CODES],
            sd_len: [5; D_CODES],
        };
        let mut length = 0usize;
        let mut code = 0usize;
        while code < LENGTH_CODES - 1 {
            t.base_length[code] = length as u16;
            for _ in 0..(1usize << EXTRA_LBITS[code]) {
                t.length_code[length] = code as u8;
                length += 1;
            }
            code += 1;
        }
        t.length_code[length - 1] = code as u8;

        let mut dist = 0usize;
        code = 0;
        while code < 16 {
            t.base_dist[code] = dist as u16;
            for _ in 0..(1usize << EXTRA_DBITS[code]) {
                t.dist_code[dist] = code as u8;
                dist += 1;
            }
            code += 1;
        }
        dist >>= 7;
        while code < D_CODES {
            t.base_dist[code] = (dist << 7) as u16;
            for _ in 0..(1usize << (EXTRA_DBITS[code] - 7)) {
                t.dist_code[256 + dist] = code as u8;
                dist += 1;
            }
            code += 1;
        }

        let mut bl_count = [0u16; MAX_BITS + 1];
        for n in 0..(L_CODES + 2) {
            let l = match n {
                0..=143 => 8,
                144..=255 => 9,
                256..=279 => 7,
                _ => 8,
            };
            t.sl_len[n] = l;
            bl_count[l as usize] += 1;
        }
        gen_codes(&mut t.sl_code, &t.sl_len, L_CODES + 1, &bl_count);
        for n in 0..D_CODES {
            t.sd_code[n] = bi_reverse(n as u32, 5) as u16;
        }
        t
    })
}

#[inline]
fn d_code(t: &Tables, dist: usize) -> usize {
    if dist < 256 {
        t.dist_code[dist] as usize
    } else {
        t.dist_code[256 + (dist >> 7)] as usize
    }
}

// Split disjoint word slices without allocating or retaining overlapping borrows.
struct Words<'w> {
    bytes: &'w mut [u16],
}
impl<'w> Words<'w> {
    fn take(&mut self, count: usize) -> &'w mut [u16] {
        let (taken, remaining) = std::mem::take(&mut self.bytes).split_at_mut(count);
        self.bytes = remaining;
        taken
    }
}
struct Output<'o> {
    bytes: &'o mut [u8],
    used: usize,
    failed: bool,
}
impl Output<'_> {
    fn extend_from_slice(&mut self, input: &[u8]) {
        if input.len() > self.bytes.len() - self.used {
            self.failed = true;
            return;
        }
        self.bytes[self.used..self.used + input.len()].copy_from_slice(input);
        self.used += input.len();
    }
    fn push(&mut self, byte: u8) {
        self.extend_from_slice(&[byte]);
    }
}

/// `ct_data`, with the `fc` (freq/code) and `dl` (dad/len) unions kept as separate arrays.
struct Tree<'w> {
    fc: &'w mut [u16],
    dl: &'w mut [u16],
}

impl<'w> Tree<'w> {
    fn new(n: usize, workspace: &mut Words<'w>) -> Self {
        Self {
            fc: workspace.take(n),
            dl: workspace.take(n),
        }
    }
}

struct Desc<'a> {
    stree_len: Option<&'a [u16]>,
    extra: &'a [u8],
    base: usize,
    elems: usize,
    max_length: usize,
}

/// Scratch state shared by the three `build_tree` invocations.
struct Ctx {
    heap: [usize; HEAP_SIZE],
    depth: [u8; HEAP_SIZE],
    bl_count: [u16; MAX_BITS + 1],
    heap_len: usize,
    heap_max: usize,
    opt_len: u64,
    static_len: u64,
}

#[inline]
fn smaller(fc: &[u16], depth: &[u8], n: usize, m: usize) -> bool {
    fc[n] < fc[m] || (fc[n] == fc[m] && depth[n] <= depth[m])
}

fn pqdownheap(ctx: &mut Ctx, fc: &[u16], mut k: usize) {
    let v = ctx.heap[k];
    let mut j = k << 1;
    while j <= ctx.heap_len {
        if j < ctx.heap_len && smaller(fc, &ctx.depth, ctx.heap[j + 1], ctx.heap[j]) {
            j += 1;
        }
        if smaller(fc, &ctx.depth, v, ctx.heap[j]) {
            break;
        }
        ctx.heap[k] = ctx.heap[j];
        k = j;
        j <<= 1;
    }
    ctx.heap[k] = v;
}

fn gen_bitlen(ctx: &mut Ctx, tree: &mut Tree, max_code: usize, desc: &Desc) {
    let mut overflow: i32 = 0;
    ctx.bl_count = [0; MAX_BITS + 1];

    let root = ctx.heap[ctx.heap_max];
    tree.dl[root] = 0;

    let mut h = ctx.heap_max + 1;
    while h < HEAP_SIZE {
        let n = ctx.heap[h];
        let mut bits = tree.dl[tree.dl[n] as usize] as usize + 1;
        if bits > desc.max_length {
            bits = desc.max_length;
            overflow += 1;
        }
        tree.dl[n] = bits as u16;
        h += 1;
        if n > max_code {
            continue;
        }
        ctx.bl_count[bits] += 1;
        let xbits = if n >= desc.base {
            desc.extra[n - desc.base] as usize
        } else {
            0
        };
        let f = u64::from(tree.fc[n]);
        ctx.opt_len = ctx.opt_len.wrapping_add(f * (bits + xbits) as u64);
        if let Some(st) = desc.stree_len {
            ctx.static_len = ctx
                .static_len
                .wrapping_add(f * (st[n] as usize + xbits) as u64);
        }
    }
    if overflow == 0 {
        return;
    }

    loop {
        let mut bits = desc.max_length - 1;
        while ctx.bl_count[bits] == 0 {
            bits -= 1;
        }
        ctx.bl_count[bits] -= 1;
        ctx.bl_count[bits + 1] += 2;
        ctx.bl_count[desc.max_length] -= 1;
        overflow -= 2;
        if overflow <= 0 {
            break;
        }
    }

    // h is still HEAP_SIZE here.
    let mut bits = desc.max_length;
    while bits != 0 {
        let mut n = ctx.bl_count[bits];
        while n != 0 {
            h -= 1;
            let m = ctx.heap[h];
            if m > max_code {
                continue;
            }
            if tree.dl[m] as usize != bits {
                let diff = (bits as u64).wrapping_sub(u64::from(tree.dl[m]));
                ctx.opt_len = ctx
                    .opt_len
                    .wrapping_add(diff.wrapping_mul(u64::from(tree.fc[m])));
                tree.dl[m] = bits as u16;
            }
            n -= 1;
        }
        bits -= 1;
    }
}

/// `build_tree`; returns `max_code`.
fn build_tree(ctx: &mut Ctx, tree: &mut Tree, desc: &Desc) -> usize {
    let elems = desc.elems;
    let mut max_code: isize = -1;
    ctx.heap_len = 0;
    ctx.heap_max = HEAP_SIZE;

    for n in 0..elems {
        if tree.fc[n] != 0 {
            ctx.heap_len += 1;
            ctx.heap[ctx.heap_len] = n;
            max_code = n as isize;
            ctx.depth[n] = 0;
        } else {
            tree.dl[n] = 0;
        }
    }

    while ctx.heap_len < 2 {
        let node = if max_code < 2 {
            max_code += 1;
            max_code as usize
        } else {
            0
        };
        ctx.heap_len += 1;
        ctx.heap[ctx.heap_len] = node;
        tree.fc[node] = 1;
        ctx.depth[node] = 0;
        ctx.opt_len = ctx.opt_len.wrapping_sub(1);
        if let Some(st) = desc.stree_len {
            ctx.static_len = ctx.static_len.wrapping_sub(u64::from(st[node]));
        }
    }
    let max_code = max_code as usize;

    let mut n = ctx.heap_len / 2;
    while n >= 1 {
        pqdownheap(ctx, tree.fc, n);
        n -= 1;
    }

    let mut node = elems;
    loop {
        // pqremove
        let n = ctx.heap[1];
        ctx.heap[1] = ctx.heap[ctx.heap_len];
        ctx.heap_len -= 1;
        pqdownheap(ctx, tree.fc, 1);
        let m = ctx.heap[1];

        ctx.heap_max -= 1;
        ctx.heap[ctx.heap_max] = n;
        ctx.heap_max -= 1;
        ctx.heap[ctx.heap_max] = m;

        tree.fc[node] = tree.fc[n].wrapping_add(tree.fc[m]);
        ctx.depth[node] = ctx.depth[n].max(ctx.depth[m]) + 1;
        tree.dl[n] = node as u16;
        tree.dl[m] = node as u16;

        ctx.heap[1] = node;
        node += 1;
        pqdownheap(ctx, tree.fc, 1);
        if ctx.heap_len < 2 {
            break;
        }
    }

    ctx.heap_max -= 1;
    ctx.heap[ctx.heap_max] = ctx.heap[1];

    gen_bitlen(ctx, tree, max_code, desc);
    let bl_count = ctx.bl_count;
    gen_codes(tree.fc, tree.dl, max_code, &bl_count);
    max_code
}

/// Little-endian bit writer (deflate bit order).
struct BitOut<'o> {
    out: Output<'o>,
    acc: u64,
    nbits: u32,
}

impl BitOut<'_> {
    #[inline]
    fn send_bits(&mut self, value: u32, len: u32) {
        self.acc |= u64::from(value) << self.nbits;
        self.nbits += len;
        if self.nbits >= 32 {
            self.out.extend_from_slice(&(self.acc as u32).to_le_bytes());
            self.acc >>= 32;
            self.nbits -= 32;
        }
    }

    /// `bi_windup`: flush to a byte boundary.
    fn windup(&mut self) {
        while self.nbits > 0 {
            self.out.push(self.acc as u8);
            self.acc >>= 8;
            self.nbits = self.nbits.saturating_sub(8);
        }
        self.acc = 0;
    }
}

struct Trees<'w> {
    l: Tree<'w>,
    d: Tree<'w>,
    bl: Tree<'w>,
    ctx: Ctx,
    l_max: usize,
    d_max: usize,
    d_buf: &'w mut [u16],
    l_buf: &'w mut [u8],
    sym_next: usize,
}

impl<'w> Trees<'w> {
    fn new(workspace: &mut Words<'w>, literals: &'w mut [u8]) -> Self {
        let mut s = Self {
            l: Tree::new(HEAP_SIZE, workspace),
            d: Tree::new(2 * D_CODES + 1, workspace),
            bl: Tree::new(2 * BL_CODES + 1, workspace),
            ctx: Ctx {
                heap: [0; HEAP_SIZE],
                depth: [0; HEAP_SIZE],
                bl_count: [0; MAX_BITS + 1],
                heap_len: 0,
                heap_max: 0,
                opt_len: 0,
                static_len: 0,
            },
            l_max: 0,
            d_max: 0,
            d_buf: workspace.take(LIT_BUFSIZE),
            l_buf: literals,
            sym_next: 0,
        };
        s.init_block();
        s
    }

    fn init_block(&mut self) {
        self.l.fc[..L_CODES].fill(0);
        self.d.fc[..D_CODES].fill(0);
        self.bl.fc[..BL_CODES].fill(0);
        self.l.fc[END_BLOCK] = 1;
        self.ctx.opt_len = 0;
        self.ctx.static_len = 0;
        self.sym_next = 0;
    }

    /// `_tr_tally`; true when the symbol buffer is full.
    #[inline]
    fn tally(&mut self, dist: usize, lc: usize) -> bool {
        self.d_buf[self.sym_next] = dist as u16;
        self.l_buf[self.sym_next] = lc as u8;
        self.sym_next += 1;
        if dist == 0 {
            self.l.fc[lc] += 1;
        } else {
            let t = tables();
            let dd = dist - 1;
            self.l.fc[t.length_code[lc] as usize + LITERALS + 1] += 1;
            self.d.fc[d_code(t, dd)] += 1;
        }
        self.sym_next == SYM_END
    }

    fn scan_tree(bl: &mut Tree, tree: &mut Tree, max_code: usize) {
        let mut prevlen: i32 = -1;
        let mut nextlen = tree.dl[0] as i32;
        let mut count = 0;
        let (mut max_count, mut min_count) = (7, 4);
        if nextlen == 0 {
            max_count = 138;
            min_count = 3;
        }
        tree.dl[max_code + 1] = 0xffff;
        for n in 0..=max_code {
            let curlen = nextlen;
            nextlen = tree.dl[n + 1] as i32;
            count += 1;
            if count < max_count && curlen == nextlen {
                continue;
            } else if count < min_count {
                bl.fc[curlen as usize] = bl.fc[curlen as usize].wrapping_add(count as u16);
            } else if curlen != 0 {
                if curlen != prevlen {
                    bl.fc[curlen as usize] += 1;
                }
                bl.fc[REP_3_6] += 1;
            } else if count <= 10 {
                bl.fc[REPZ_3_10] += 1;
            } else {
                bl.fc[REPZ_11_138] += 1;
            }
            count = 0;
            prevlen = curlen;
            if nextlen == 0 {
                max_count = 138;
                min_count = 3;
            } else if curlen == nextlen {
                max_count = 6;
                min_count = 3;
            } else {
                max_count = 7;
                min_count = 4;
            }
        }
    }

    fn send_tree(out: &mut BitOut, bl: &Tree, tree: &Tree, max_code: usize) {
        let send =
            |out: &mut BitOut, c: usize| out.send_bits(u32::from(bl.fc[c]), u32::from(bl.dl[c]));
        let mut prevlen: i32 = -1;
        let mut nextlen = tree.dl[0] as i32;
        let mut count = 0;
        let (mut max_count, mut min_count) = (7, 4);
        if nextlen == 0 {
            max_count = 138;
            min_count = 3;
        }
        for n in 0..=max_code {
            let curlen = nextlen;
            nextlen = tree.dl[n + 1] as i32;
            count += 1;
            if count < max_count && curlen == nextlen {
                continue;
            } else if count < min_count {
                while count != 0 {
                    send(out, curlen as usize);
                    count -= 1;
                }
            } else if curlen != 0 {
                if curlen != prevlen {
                    send(out, curlen as usize);
                    count -= 1;
                }
                send(out, REP_3_6);
                out.send_bits(count as u32 - 3, 2);
            } else if count <= 10 {
                send(out, REPZ_3_10);
                out.send_bits(count as u32 - 3, 3);
            } else {
                send(out, REPZ_11_138);
                out.send_bits(count as u32 - 11, 7);
            }
            count = 0;
            prevlen = curlen;
            if nextlen == 0 {
                max_count = 138;
                min_count = 3;
            } else if curlen == nextlen {
                max_count = 6;
                min_count = 3;
            } else {
                max_count = 7;
                min_count = 4;
            }
        }
    }

    fn build_bl_tree(&mut self) -> usize {
        Self::scan_tree(&mut self.bl, &mut self.l, self.l_max);
        Self::scan_tree(&mut self.bl, &mut self.d, self.d_max);
        let desc = Desc {
            stree_len: None,
            extra: &EXTRA_BLBITS,
            base: 0,
            elems: BL_CODES,
            max_length: 7,
        };
        build_tree(&mut self.ctx, &mut self.bl, &desc);
        let mut max_blindex = BL_CODES - 1;
        while max_blindex >= 3 {
            if self.bl.dl[BL_ORDER[max_blindex]] != 0 {
                break;
            }
            max_blindex -= 1;
        }
        self.ctx.opt_len = self
            .ctx
            .opt_len
            .wrapping_add(3 * (max_blindex as u64 + 1) + 5 + 5 + 4);
        max_blindex
    }

    fn compress_block(
        &self,
        out: &mut BitOut,
        lcode: &[u16],
        llen: &[u16],
        dcode: &[u16],
        dlen: &[u16],
    ) {
        let t = tables();
        for sx in 0..self.sym_next {
            let dist = self.d_buf[sx] as usize;
            let mut lc = self.l_buf[sx] as usize;
            if dist == 0 {
                out.send_bits(u32::from(lcode[lc]), u32::from(llen[lc]));
            } else {
                let code = t.length_code[lc] as usize;
                let c = code + LITERALS + 1;
                out.send_bits(u32::from(lcode[c]), u32::from(llen[c]));
                let extra = EXTRA_LBITS[code];
                if extra != 0 {
                    lc -= t.base_length[code] as usize;
                    out.send_bits(lc as u32, u32::from(extra));
                }
                let dd = dist - 1;
                let code = d_code(t, dd);
                out.send_bits(u32::from(dcode[code]), u32::from(dlen[code]));
                let extra = EXTRA_DBITS[code];
                if extra != 0 {
                    let dd = dd - t.base_dist[code] as usize;
                    out.send_bits(dd as u32, u32::from(extra));
                }
            }
        }
        out.send_bits(u32::from(lcode[END_BLOCK]), u32::from(llen[END_BLOCK]));
    }

    /// `_tr_flush_block` for level > 0 with the default strategy.
    fn flush_block(&mut self, out: &mut BitOut, buf: Option<&[u8]>, stored_len: usize, last: bool) {
        let t = tables();
        let ld = Desc {
            stree_len: Some(&t.sl_len),
            extra: &EXTRA_LBITS,
            base: LITERALS + 1,
            elems: L_CODES,
            max_length: MAX_BITS,
        };
        let dd = Desc {
            stree_len: Some(&t.sd_len),
            extra: &EXTRA_DBITS,
            base: 0,
            elems: D_CODES,
            max_length: MAX_BITS,
        };
        self.l_max = build_tree(&mut self.ctx, &mut self.l, &ld);
        self.d_max = build_tree(&mut self.ctx, &mut self.d, &dd);
        let max_blindex = self.build_bl_tree();

        let mut opt_lenb = (self.ctx.opt_len + 3 + 7) >> 3;
        let static_lenb = (self.ctx.static_len + 3 + 7) >> 3;
        if static_lenb <= opt_lenb {
            opt_lenb = static_lenb;
        }

        let last_bit = u32::from(last);
        match buf {
            Some(data) if stored_len as u64 + 4 <= opt_lenb => {
                out.send_bits(last_bit, 3);
                out.windup();
                let len = stored_len as u16;
                out.out.extend_from_slice(&len.to_le_bytes());
                out.out.extend_from_slice(&(!len).to_le_bytes());
                out.out.extend_from_slice(&data[..stored_len]);
            }
            _ if static_lenb == opt_lenb => {
                out.send_bits((1 << 1) + last_bit, 3);
                self.compress_block(out, &t.sl_code, &t.sl_len, &t.sd_code, &t.sd_len);
            }
            _ => {
                out.send_bits((2 << 1) + last_bit, 3);
                out.send_bits((self.l_max + 1 - 257) as u32, 5);
                out.send_bits((self.d_max + 1 - 1) as u32, 5);
                out.send_bits((max_blindex + 1 - 4) as u32, 4);
                for &o in BL_ORDER.iter().take(max_blindex + 1) {
                    out.send_bits(u32::from(self.bl.dl[o]), 3);
                }
                Self::send_tree(out, &self.bl, &self.l, self.l_max);
                Self::send_tree(out, &self.bl, &self.d, self.d_max);
                self.compress_block(out, self.l.fc, self.l.dl, self.d.fc, self.d.dl);
            }
        }
        self.init_block();
        if last {
            out.windup();
        }
    }
}

/// Number of equal leading bytes of two slices (over the shorter length).
#[inline]
fn common_prefix(a: &[u8], b: &[u8]) -> usize {
    let n = a.len().min(b.len());
    let mut i = 0;
    while i + 8 <= n {
        let x = u64::from_le_bytes(a[i..i + 8].try_into().unwrap());
        let y = u64::from_le_bytes(b[i..i + 8].try_into().unwrap());
        let d = x ^ y;
        if d != 0 {
            return i + (d.trailing_zeros() / 8) as usize;
        }
        i += 8;
    }
    while i < n && a[i] == b[i] {
        i += 1;
    }
    i
}

struct Deflate<'a, 'w, 'o> {
    input: &'a [u8],
    in_pos: usize,
    window: &'w mut [u8],
    prev: &'w mut [u16],
    head: &'w mut [u16],
    ins_h: u32,
    strstart: usize,
    block_start: i64,
    lookahead: usize,
    insert: usize,
    match_length: usize,
    prev_length: usize,
    match_start: usize,
    prev_match: usize,
    match_available: bool,
    trees: Trees<'w>,
    bits: BitOut<'o>,
}

impl<'a, 'w, 'o> Deflate<'a, 'w, 'o> {
    fn new(
        input: &'a [u8],
        output: &'o mut [u8],
        window: &'w mut [u8],
        workspace: &mut Words<'w>,
        literals: &'w mut [u8],
    ) -> Self {
        Self {
            input,
            in_pos: 0,
            window,
            prev: workspace.take(W_SIZE),
            head: workspace.take(HASH_SIZE),
            ins_h: 0,
            strstart: 0,
            block_start: 0,
            lookahead: 0,
            insert: 0,
            match_length: MIN_MATCH - 1,
            prev_length: MIN_MATCH - 1,
            match_start: 0,
            prev_match: 0,
            match_available: false,
            trees: Trees::new(workspace, literals),
            bits: BitOut {
                out: Output {
                    bytes: output,
                    used: 0,
                    failed: false,
                },
                acc: 0,
                nbits: 0,
            },
        }
    }

    #[inline]
    fn update_hash(h: u32, c: u8) -> u32 {
        ((h << HASH_SHIFT) ^ u32::from(c)) & HASH_MASK
    }

    #[inline]
    fn insert_string(&mut self, s: usize) -> usize {
        self.ins_h = Self::update_hash(self.ins_h, self.window[s + MIN_MATCH - 1]);
        let h = self.head[self.ins_h as usize];
        self.prev[s & W_MASK] = h;
        self.head[self.ins_h as usize] = s as u16;
        h as usize
    }

    fn slide_hash(&mut self) {
        let w = W_SIZE as u16;
        for p in self.head.iter_mut() {
            *p = p.saturating_sub(w);
        }
        for p in self.prev.iter_mut() {
            *p = p.saturating_sub(w);
        }
    }

    fn fill_window(&mut self) {
        loop {
            let mut more = WINDOW_SIZE - self.lookahead - self.strstart;
            if self.strstart >= W_SIZE + MAX_DIST {
                self.window.copy_within(W_SIZE..W_SIZE + (W_SIZE - more), 0);
                self.match_start = self.match_start.wrapping_sub(W_SIZE);
                self.strstart -= W_SIZE;
                self.block_start -= W_SIZE as i64;
                if self.insert > self.strstart {
                    self.insert = self.strstart;
                }
                self.slide_hash();
                more += W_SIZE;
            }
            let avail = self.input.len() - self.in_pos;
            if avail == 0 {
                break;
            }
            let n = avail.min(more);
            let dst = self.strstart + self.lookahead;
            self.window[dst..dst + n].copy_from_slice(&self.input[self.in_pos..self.in_pos + n]);
            self.in_pos += n;
            self.lookahead += n;

            if self.lookahead + self.insert >= MIN_MATCH {
                let mut str = self.strstart - self.insert;
                self.ins_h = u32::from(self.window[str]);
                self.ins_h = Self::update_hash(self.ins_h, self.window[str + 1]);
                while self.insert > 0 {
                    self.ins_h = Self::update_hash(self.ins_h, self.window[str + MIN_MATCH - 1]);
                    self.prev[str & W_MASK] = self.head[self.ins_h as usize];
                    self.head[self.ins_h as usize] = str as u16;
                    str += 1;
                    self.insert -= 1;
                    if self.lookahead + self.insert < MIN_MATCH {
                        break;
                    }
                }
            }
            if !(self.lookahead < MIN_LOOKAHEAD && self.in_pos != self.input.len()) {
                break;
            }
        }
    }

    fn longest_match(&mut self, mut cur_match: usize) -> usize {
        let mut chain_length = MAX_CHAIN;
        let strstart = self.strstart;
        let mut best_len = self.prev_length;
        let mut nice_match = NICE_LENGTH;
        let limit = strstart.saturating_sub(MAX_DIST);
        let w = &self.window[..];
        let mut scan_end1 = w[strstart + best_len - 1];
        let mut scan_end = w[strstart + best_len];
        if self.prev_length >= GOOD_LENGTH {
            chain_length >>= 2;
        }
        if nice_match > self.lookahead {
            nice_match = self.lookahead;
        }
        let s0 = w[strstart];
        let s1 = w[strstart + 1];
        loop {
            let m = cur_match;
            if w[m + best_len] == scan_end
                && w[m + best_len - 1] == scan_end1
                && w[m] == s0
                && w[m + 1] == s1
            {
                // scan[2] == match[2] is implied by equal hash keys, as in C.
                let len = MIN_MATCH
                    + common_prefix(
                        &w[strstart + 3..strstart + MAX_MATCH],
                        &w[m + 3..m + MAX_MATCH],
                    );
                if len > best_len {
                    self.match_start = cur_match;
                    best_len = len;
                    if len >= nice_match {
                        break;
                    }
                    scan_end1 = w[strstart + best_len - 1];
                    scan_end = w[strstart + best_len];
                }
            }
            cur_match = self.prev[cur_match & W_MASK] as usize;
            if cur_match <= limit {
                break;
            }
            chain_length -= 1;
            if chain_length == 0 {
                break;
            }
        }
        best_len.min(self.lookahead)
    }

    fn flush_block(&mut self, last: bool) {
        let stored_len = (self.strstart as i64 - self.block_start) as usize;
        let buf = if self.block_start >= 0 {
            let b = self.block_start as usize;
            Some(&self.window[b..b + stored_len])
        } else {
            None
        };
        self.trees
            .flush_block(&mut self.bits, buf, stored_len, last);
        self.block_start = self.strstart as i64;
    }

    /// `deflate_slow(s, Z_FINISH)`.
    fn deflate_slow(&mut self) {
        loop {
            if self.lookahead < MIN_LOOKAHEAD {
                self.fill_window();
                if self.lookahead == 0 {
                    break;
                }
            }
            let mut hash_head = 0;
            if self.lookahead >= MIN_MATCH {
                hash_head = self.insert_string(self.strstart);
            }
            self.prev_length = self.match_length;
            self.prev_match = self.match_start;
            self.match_length = MIN_MATCH - 1;

            if hash_head != 0
                && self.prev_length < MAX_LAZY
                && self.strstart.wrapping_sub(hash_head) <= MAX_DIST
            {
                self.match_length = self.longest_match(hash_head);
                if self.match_length <= 5
                    && self.match_length == MIN_MATCH
                    && self.strstart.wrapping_sub(self.match_start) > TOO_FAR
                {
                    self.match_length = MIN_MATCH - 1;
                }
            }

            if self.prev_length >= MIN_MATCH && self.match_length <= self.prev_length {
                let max_insert = self.strstart + self.lookahead - MIN_MATCH;
                let bflush = self.trees.tally(
                    self.strstart - 1 - self.prev_match,
                    self.prev_length - MIN_MATCH,
                );
                self.lookahead -= self.prev_length - 1;
                self.prev_length -= 2;
                loop {
                    self.strstart += 1;
                    if self.strstart <= max_insert {
                        self.insert_string(self.strstart);
                    }
                    self.prev_length -= 1;
                    if self.prev_length == 0 {
                        break;
                    }
                }
                self.match_available = false;
                self.match_length = MIN_MATCH - 1;
                self.strstart += 1;
                if bflush {
                    self.flush_block(false);
                }
            } else if self.match_available {
                let lit = self.window[self.strstart - 1] as usize;
                let bflush = self.trees.tally(0, lit);
                if bflush {
                    self.flush_block(false);
                }
                self.strstart += 1;
                self.lookahead -= 1;
            } else {
                self.match_available = true;
                self.strstart += 1;
                self.lookahead -= 1;
            }
        }
        if self.match_available {
            let lit = self.window[self.strstart - 1] as usize;
            self.trees.tally(0, lit);
            self.match_available = false;
        }
        self.insert = self.strstart.min(MIN_MATCH - 1);
        self.flush_block(true);
    }
}

/// Write a gzip stream matching classic zlib level 6, default strategy,
/// memLevel 8, one Z_FINISH call, with the Defender NTFS OS header byte (10).
/// No heap allocations occur. Returns None when output/scratch is too small.
/// Scratch needs at least 300,000 bytes, with arbitrary alignment accepted.
pub fn gzip_level6(input: &[u8], output: &mut [u8], scratch: &mut [u8]) -> Option<usize> {
    if input.len() > u32::MAX as usize || output.len() < 18 || scratch.len() < 300000 {
        return None;
    }
    scratch.fill(0);
    output[..10].copy_from_slice(&[31, 139, 8, 0, 0, 0, 0, 0, 0, 10]);
    let (window, rest) = scratch.split_at_mut(WINDOW_SIZE);
    let (literals, rest) = rest.split_at_mut(LIT_BUFSIZE);
    // SAFETY: u16 has no invalid bit patterns. align_to_mut partitions the
    // exclusive scratch slice; its aligned words remain borrowed until return.
    let (_, words, _) = unsafe { rest.align_to_mut::<u16>() };
    let mut workspace = Words { bytes: words };
    let end = output.len() - 8;
    let body_length = {
        let mut compressor = Deflate::new(
            input,
            &mut output[10..end],
            window,
            &mut workspace,
            literals,
        );
        compressor.deflate_slow();
        if compressor.bits.out.failed {
            return None;
        }
        compressor.bits.out.used
    };
    let trailer = 10 + body_length;
    output[trailer..trailer + 4].copy_from_slice(&super::crc32::crc32(0, input).to_le_bytes());
    output[trailer + 4..trailer + 8].copy_from_slice(&(input.len() as u32).to_le_bytes());
    Some(trailer + 8)
}
